version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "django"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
