# Generated by Django 6.0.1 on 2026-02-02 03:22

import django.db.models.deletion
import django.utils.timezone
import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', stocks.models.UppercaseCharField(max_length=16)),
                ('region', stocks.models.UppercaseCharField(default='US', max_length=8)),
                ('company_name', models.CharField(max_length=255)),
                ('currency_code', stocks.models.UppercaseCharField(default='USD', max_length=3)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'region'], name='stocks_stoc_ticker_1eccb9_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'region'), name='uniq_stock_ticker_region')],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('as_of_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blurb', models.TextField(blank=True, default='')),
                ('rating', stocks.models.NormalizedRatingField(blank=True, default='', max_length=20)),
                ('analyst_team', models.CharField(blank=True, default='', max_length=128)),
                ('report_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('raw_text', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('price_objective', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('upside', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('average_daily_value', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stocks.stock')),
            ],
            options={
                'ordering': ['-as_of_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EPSForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('eps', models.DecimalField(decimal_places=6, max_digits=18)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eps_forecasts', to='stocks.dailyreport')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='stocks_epsf_year_0b34a7_idx'), models.Index(fields=['report', 'year'], name='stocks_epsf_report__d05a60_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'year'), name='uniq_eps_year_per_report')],
            },
        ),
        migrations.CreateModel(
            name='ReportKeyTakeaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_takeaways', to='stocks.dailyreport')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['report', 'order'], name='stocks_repo_report__69fc37_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'order'), name='uniq_takeaway_order_per_report')],
            },
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['stock', '-as_of_timestamp'], name='stocks_dail_stock_i_4532ef_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['stock', 'rating', '-as_of_timestamp'], name='stocks_dail_stock_i_2f4b92_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('stock', 'as_of_timestamp'), name='uniq_report_as_of_timestamp_per_stock'),
        ),
    ]
