# Generated by Django 6.0.1 on 2026-02-02 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=24)),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_snapshots', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'stock', '-as_of'], name='investor_ho_user_id_f31c8f_idx'), models.Index(fields=['user', '-as_of'], name='investor_ho_user_id_99fd60_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'stock', 'as_of'), name='uniq_snap_user_stock_as_of')],
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='investor_wa_user_id_ae972d_idx'), models.Index(fields=['stock'], name='investor_wa_stock_i_6f350b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'stock'), name='uniq_watch_user_stock')],
            },
        ),
    ]
